language: ruby
cache: bundle
sudo: false
rvm:
  - 2.3.0
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
gemfile:
  - gemfiles/Gemfile.actionpack5.0.0.beta4
  - gemfiles/Gemfile.actionpack4.0
  - Gemfile
script: bundle exec rake
